### ISSUE TITLE
Prepare fails while following exact steps on clean Ubuntu 22.04

### ISSUE THREAD

**Issue by m-from-space** [renpy/renpy-build#91]
1. Installed a clean Ubuntu 22.04.3 into a VirtualBox (6.1) environment.
2. Created a user "rb" as instructed and made it root.
3. Cloned `renpy-build` and hit `./prepare.sh`

After many lines of preparing, an error occured:

```
gen3/renpy.text.hbfont.c:755:10: fatal error: hb.h: No such file or directory
  755 | #include "hb.h"
      |          ^~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

Sad face. :(

Update: preparing works fine on clean install of Ubuntu 22.10.1 (besides some deprecation warnings and the like).

**Comment by azazar** [comment]
On Ubuntu 20.04 it fails too.

# Dockerfile
```
# Use an official Ubuntu runtime as a parent image
FROM ubuntu:20.04

# Set the working directory in the container
WORKDIR /opt

# Install renpy-build dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git build-essential ccache unzip autoconf autoconf-archive automake libtool-bin \
        python2-dev python3-dev python3-venv \
        curl \
        python3-jinja2 \
        debootstrap qemu-user-static \
        libgmp-dev libmpfr-dev libmpc-dev \
        libssl-dev libbz2-dev liblzma-dev \
        cmake clang libxml2-dev llvm \
        quilt \
        libavcodec-dev libavformat-dev \
        libswresample-dev libswscale-dev libfreetype6-dev libfribidi-dev libsdl2-dev \
        libsdl2-image-dev libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-ttf-dev libjpeg-dev \
        lsb-release wget software-properties-common gnupg \
 && rm -rf /var/lib/apt/lists/*

# Clone the renpy-build repository
RUN git clone https://github.com/renpy/renpy-build.git

RUN echo -e '#!/bin/bash\n\neval "$@"' > /usr/local/bin/sudo \
 && chmod +x /usr/local/bin/sudo

# Set up the Ren'Py SDK (adjust the version as needed)
RUN cd renpy-build \
    && ./prepare.sh \
    && ./build.py

# Build Ren'Py for the web
RUN cd renpy-build \
 && BASE=. bash ./nightly/git.sh \
 && ./build.py --platform web
```

# Error Message
```
...
#9 231.4 - renpy.text.textsupport ------------------------------------------------------
#9 231.4 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
#9 ERROR: process "/bin/sh -c cd renpy-build     && ./prepare.sh     && ./build.py" did not complete successfully: exit code: 255
------
 > [6/7] RUN cd renpy-build     && ./prepare.sh     && ./build.py:
231.4 - renpy.styledata.style_insensitive_functions ---------------------------------
231.4 - renpy.display.accelerator ---------------------------------------------------
231.4 - renpy.styledata.style_functions ---------------------------------------------
231.4 - renpy.gl2.gl2texture --------------------------------------------------------
231.4 - renpy.gl.gldraw -------------------------------------------------------------
231.4 - renpy.gl.gltexture ----------------------------------------------------------
231.4 - renpy.gl2.gl2draw -----------------------------------------------------------
231.4 - renpy.uguu.uguu -------------------------------------------------------------
231.4 - renpy.text.textsupport ------------------------------------------------------
231.4 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
------
Dockerfile:31
--------------------
  30 |     # Set up the Ren'Py SDK (adjust the version as needed)
  31 | >>> RUN cd renpy-build \
  32 | >>>     && ./prepare.sh \
  33 | >>>     && ./build.py
  34 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd renpy-build     && ./prepare.sh     && ./build.py" did not complete successfully: exit code: 255
```

**Comment by azazar** [comment]
Installing `libharfbuzz-dev` didn't help. It still fails.

# Output
```
...
#9 231.7 - renpy.styledata.style_functions ---------------------------------------------
#9 231.7 - renpy.gl.gldraw -------------------------------------------------------------
#9 231.7 - renpy.gl2.gl2draw -----------------------------------------------------------
#9 231.7 - renpy.uguu.uguu -------------------------------------------------------------
#9 231.7 - renpy.gl.gltexture ----------------------------------------------------------
#9 231.7 - renpy.text.textsupport ------------------------------------------------------
#9 242.0 /opt/renpy-build
#9 242.1 Traceback (most recent call last):
#9 242.1   File "./build.py", line 11, in <module>
#9 242.1     from renpybuild.context import Context
#9 242.1   File "/opt/renpy-build/renpybuild/context.py", line 9, in <module>
#9 242.1     import renpybuild.run
#9 242.1   File "/opt/renpy-build/renpybuild/run.py", line 11, in <module>
#9 242.1     emsdk_cache : dict[str, str] = { }
#9 242.1 TypeError: 'type' object is not subscriptable
#9 ERROR: process "/bin/sh -c cd renpy-build     && ./prepare.sh     && ./build.py" did not complete successfully: exit code: 1
------
 > [6/7] RUN cd renpy-build     && ./prepare.sh     && ./build.py:
231.7 - renpy.text.textsupport ------------------------------------------------------
242.0 /opt/renpy-build
242.1 Traceback (most recent call last):
242.1   File "./build.py", line 11, in <module>
242.1     from renpybuild.context import Context
242.1   File "/opt/renpy-build/renpybuild/context.py", line 9, in <module>
242.1     import renpybuild.run
242.1   File "/opt/renpy-build/renpybuild/run.py", line 11, in <module>
242.1     emsdk_cache : dict[str, str] = { }
242.1 TypeError: 'type' object is not subscriptable
------
Dockerfile:32
--------------------
  31 |     # Set up the Ren'Py SDK (adjust the version as needed)
  32 | >>> RUN cd renpy-build \
  33 | >>>     && ./prepare.sh \
  34 | >>>     && ./build.py
  35 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd renpy-build     && ./prepare.sh     && ./build.py" did not complete successfully: exit code: 1
```

**Comment by renpytom** [comment]
I've raised the dependency to Ubuntu 23.10, which is what I develop Ren'Py on.
