### ISSUE TITLE
Prepare fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by Tey** [renpy/renpy-build#58]
Building pygame_sdl2 now requires libsdl2-image 2.6.0 since [this PR](https://github.com/renpy/pygame_sdl2/pull/142) has been merged, but Ubuntu 22.04 is stuck on [2.0.x](https://packages.ubuntu.com/jammy/libsdl2-image-2.0-0), so "prepare.sh" fails eventually:
<details><summary>Errors log</summary>

```
gen3/pygame_sdl2.image.c: In function ‘__pyx_pf_11pygame_sdl2_5image_init’:
gen3/pygame_sdl2.image.c:1669:126: error: ‘IMG_INIT_JXL’ undeclared (first use in this function); did you mean ‘IMG_INIT_JPG’?
 1669 |   __pyx_v_11pygame_sdl2_5image_image_formats = IMG_Init((((((IMG_INIT_JPG | IMG_INIT_PNG) | IMG_INIT_TIF) | IMG_INIT_WEBP) | IMG_INIT_JXL) | IMG_INIT_AVIF));
      |                                                                                                                              ^~~~~~~~~~~~
      |                                                                                                                              IMG_INIT_JPG
gen3/pygame_sdl2.image.c:1669:126: note: each undeclared identifier is reported only once for each function it appears in
gen3/pygame_sdl2.image.c:1669:142: error: ‘IMG_INIT_AVIF’ undeclared (first use in this function); did you mean ‘IMG_INIT_TIF’?
 1669 |   __pyx_v_11pygame_sdl2_5image_image_formats = IMG_Init((((((IMG_INIT_JPG | IMG_INIT_PNG) | IMG_INIT_TIF) | IMG_INIT_WEBP) | IMG_INIT_JXL) | IMG_INIT_AVIF));
      |                                                                                                                                              ^~~~~~~~~~~~~
      |                                                                                                                                              IMG_INIT_TIF
gen3/pygame_sdl2.image.c: In function ‘__pyx_pf_11pygame_sdl2_5image_6load’:
gen3/pygame_sdl2.image.c:2520:27: warning: implicit declaration of function ‘IMG_LoadSizedSVG_RW’; did you mean ‘IMG_LoadSVG_RW’? [-Wimplicit-function-declaration]
 2520 |             __pyx_v_img = IMG_LoadSizedSVG_RW(__pyx_v_rwops, __pyx_v_width, __pyx_v_height);
      |                           ^~~~~~~~~~~~~~~~~~~
      |                           IMG_LoadSVG_RW
gen3/pygame_sdl2.image.c:2520:25: warning: assignment to ‘SDL_Surface *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2520 |             __pyx_v_img = IMG_LoadSizedSVG_RW(__pyx_v_rwops, __pyx_v_width, __pyx_v_height);
      |                         ^
gen3/pygame_sdl2.image.c: In function ‘__pyx_pymod_exec_image’:
gen3/pygame_sdl2.image.c:4476:46: error: ‘IMG_INIT_JXL’ undeclared (first use in this function); did you mean ‘IMG_INIT_JPG’?
 4476 |   __pyx_t_2 = __Pyx_PyInt_From_IMG_InitFlags(IMG_INIT_JXL); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 48, __pyx_L1_error)
      |                                              ^~~~~~~~~~~~
      |                                              IMG_INIT_JPG
gen3/pygame_sdl2.image.c:4488:46: error: ‘IMG_INIT_AVIF’ undeclared (first use in this function); did you mean ‘IMG_INIT_TIF’?
 4488 |   __pyx_t_2 = __Pyx_PyInt_From_IMG_InitFlags(IMG_INIT_AVIF); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 49, __pyx_L1_error)
      |                                              ^~~~~~~~~~~~~
      |                                              IMG_INIT_TIF
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```
</details>

This is on latest Ubuntu 22.04 from a docker image:
```root@64c320b39856:~/renpy-build# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

It works using Ubuntu 22.10 (and maybe 23.04), but that means the [build instructions](https://github.com/renpy/renpy-build#requirements) are not valid anymore.

**Comment by Tey** [comment]
The commands stack is:
  * `./prepare.sh`
  * `. $BASE/nightly/python.sh`
  * `$BASE/renpy/run.sh launcher quit`
  * `setup "$ROOT/pygame_sdl2/"`

The build of pygame_sdl2 does not use the sdl2_image version present in "source/" but the one installed on the system, hence the error. It seems possible to ignore the error and continue as if it never happened though.
